//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DonationData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonationData()
        {
            this.MatchUp = new HashSet<MatchUp>();
        }
    
        public int DonationID { get; set; }

        [Required(ErrorMessage = "Please enter a phone number")]
        public string Name { get; set; }

        [Required, RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter a phone number")]
        public string Phone { get; set; }

        public string FoodType { get; set; }
        [Required(ErrorMessage = "Please enter a Location")]
        public string Location { get; set; }
        [Required(ErrorMessage = "Please enter a Date")]
        public string PickupDate { get; set; }
        [Required]
        public string PickupTime { get; set; }
        public string ExpireTime { get; set; }
        public string shortDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchUp> MatchUp { get; set; }
    }
}
