//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DFFEntities : DbContext
    {
        public DFFEntities()
            : base("name=DFFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DonationData> DonationData { get; set; }
        public virtual DbSet<DonorData> DonorData { get; set; }
        public virtual DbSet<MatchUp> MatchUp { get; set; }
        public virtual DbSet<ReceiverData> ReceiverData { get; set; }
    }
}
