//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonationData()
        {
            this.MatchUp = new HashSet<MatchUp>();
        }
    
        public int DonationID { get; set; }
        public int DonorID { get; set; }
        public string FoodType { get; set; }
        public string Location { get; set; }
        public System.DateTime PickupTime { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual DonorData DonorData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchUp> MatchUp { get; set; }
    }
}
