//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchUp
    {
        public int MatchID { get; set; }
        public int DonationID { get; set; }
        public int ReceiverID { get; set; }
    
        public virtual DonationData DonationData { get; set; }
        public virtual ReceiverData ReceiverData { get; set; }
    }
}
